version: "3.9"
services:

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db      
    networks:
      - ennova-network
     
  # web-api service      
  web-api:
    container_name: web-api
    image: "web-api:0.0.1"
    build: ./web.api
    ports:
      - "8089:8089"
    # environment:
      # - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/management_robot_avg_db
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=management_robot_avg_db
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=root
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true
      - MYAPP_SMTP_HOST=smtp.gmail.com
      - MYAPP_SMTP_AUTH=true
      - MYAPP_SMTP_ENABLE_STARTTLS=true
      - MYAPP_SMTP_USERNAME=belhsenbachouch55@gmail.com
      - MYAPP_SMTP_PASSWORD=???-your password-??
      - MYAPP_LINK_GLOBAL_BACKEND=http://localhost:8089
      - MYAPP_LINK_PATH_ATTACHMENT_DOWNLOAD=/user/get-photo-by-id/
      - MYAPP_PATH_RESOURCES=/app
      # - MYAPP_FILE_FORGOT_PASSWORD_HTML=/app/user/html/forgot-password.html
      # - MYAPP_FILE_CONFIRM_MAIL_HTML=/app/user/html/verify-mail-correct.html
      # - MYAPP_FILE_UPDATE_NEW_USER_HTML=/app/user/html/update-new-user.html
      # - MYAPP_FILE_DEFAULT_USER_PHOTO=/app/user/img/user.png
      - MYAPP_LINK_WEBPAGE=http://localhost:4200
      - MYAPP_LINK_LIST_USERS=http://localhost:4200/list-users
      - MYAPP_LINK_PATH_SIGNIN=/sign-in
      - MYAPP_LINK_PATH_UPDATE_PASSWORD_FORGOT=/update-password-forgot
      - MYAPP_LINK_PATH_ERROR=/page-error
    volumes:
      - web-api-src:/app
    depends_on:
      - mongodb
    networks:
      - ennova-network



  # Angular service
  # angular:
    # container_name: front-ennova
    # image: "front-ennova:0.0.1"
    # build: ./front
    # ports:
      # - "4200:4200"
    # volumes:
      # - web-front-src:/usr/share/nginx/html
    # depends_on:
      # - web-api
    # networks:
      # - ennova-network




networks:
  ennova-network:
    driver: bridge

volumes:
  web-api-src:
  mongodata: