version: "3.9"
services:

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db      
    networks:
      - ennova-network
     
     
  # MQTT X Web UI service
  mqttx-web:
    container_name: mqttx-web
    image: emqx/mqttx-web
    ports:
      - "18084:80"
    networks:
      - ennova-network

  # EMQX MQTT Broker service  https://github.com/emqx/emqx-rel/blob/master/deploy/docker/README.md
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    environment:
      EMQX_NAME: iothost-org
      EMQX_HOST: 127.0.0.1
      # -u admin  -p public change to -p @E9M7Q7X47369%
      # EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "@E9M7Q7X47369%"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc
    # depends_on:
      # - driveless-api
    networks:
      - ennova-network








networks:
  ennova-network:
    driver: bridge

volumes:
  web-api-src:
  collector-api-src:
  driveless-api-src:
  mongodata:
  # EMQX MQTT Broker volumes
  emqx-data:
  emqx-log:
  emqx-etc:
